/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BytecodesSupplierInterface extends ethers.utils.Interface {
  functions: {
    "publishBytecode(bytes)": FunctionFragment;
    "publishBytecodes(bytes[])": FunctionFragment;
    "publishingBlock(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "publishBytecode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publishBytecodes",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "publishingBlock",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "publishBytecode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishBytecodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishingBlock",
    data: BytesLike
  ): Result;

  events: {
    "BytecodePublished(bytes32,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BytecodePublished"): EventFragment;
}

export class BytecodesSupplier extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BytecodesSupplierInterface;

  functions: {
    publishBytecode(
      _bytecode: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "publishBytecode(bytes)"(
      _bytecode: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    publishBytecodes(
      _bytecodes: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "publishBytecodes(bytes[])"(
      _bytecodes: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    publishingBlock(
      bytecodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      blockNumber: BigNumber;
      0: BigNumber;
    }>;

    "publishingBlock(bytes32)"(
      bytecodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      blockNumber: BigNumber;
      0: BigNumber;
    }>;
  };

  publishBytecode(
    _bytecode: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "publishBytecode(bytes)"(
    _bytecode: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  publishBytecodes(
    _bytecodes: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "publishBytecodes(bytes[])"(
    _bytecodes: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  publishingBlock(
    bytecodeHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "publishingBlock(bytes32)"(
    bytecodeHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    publishBytecode(
      _bytecode: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "publishBytecode(bytes)"(
      _bytecode: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    publishBytecodes(
      _bytecodes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "publishBytecodes(bytes[])"(
      _bytecodes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    publishingBlock(
      bytecodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "publishingBlock(bytes32)"(
      bytecodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    BytecodePublished(
      bytecodeHash: BytesLike | null,
      bytecode: null
    ): EventFilter;
  };

  estimateGas: {
    publishBytecode(
      _bytecode: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "publishBytecode(bytes)"(
      _bytecode: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    publishBytecodes(
      _bytecodes: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "publishBytecodes(bytes[])"(
      _bytecodes: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    publishingBlock(
      bytecodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "publishingBlock(bytes32)"(
      bytecodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    publishBytecode(
      _bytecode: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "publishBytecode(bytes)"(
      _bytecode: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    publishBytecodes(
      _bytecodes: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "publishBytecodes(bytes[])"(
      _bytecodes: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    publishingBlock(
      bytecodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "publishingBlock(bytes32)"(
      bytecodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
