/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface CTMDeploymentTrackerInterface extends ethers.utils.Interface {
  functions: {
    "BRIDGE_HUB()": FunctionFragment;
    "L1_ASSET_ROUTER()": FunctionFragment;
    "acceptOwnership()": FunctionFragment;
    "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)": FunctionFragment;
    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)": FunctionFragment;
    "bridgehubDeposit(uint256,address,uint256,bytes)": FunctionFragment;
    "calculateAssetId(address)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingOwner()": FunctionFragment;
    "registerCTMAssetOnL1(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setCtmAssetHandlerAddressOnL1(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BRIDGE_HUB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "L1_ASSET_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeCheckCounterpartAddress",
    values: [BigNumberish, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgehubConfirmL2Transaction",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgehubDeposit",
    values: [BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateAssetId",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerCTMAssetOnL1",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCtmAssetHandlerAddressOnL1",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "BRIDGE_HUB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "L1_ASSET_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgeCheckCounterpartAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgehubConfirmL2Transaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgehubDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateAssetId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCTMAssetOnL1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCtmAssetHandlerAddressOnL1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferStarted(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class CTMDeploymentTracker extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: CTMDeploymentTrackerInterface;

  functions: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    acceptOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "acceptOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    bridgeCheckCounterpartAddress(
      arg0: BigNumberish,
      arg1: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _originalCaller: string,
      arg2: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      arg2: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    calculateAssetId(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "calculateAssetId(address)"(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    initialize(
      _owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address)"(
      _owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    pendingOwner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "pendingOwner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    registerCTMAssetOnL1(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerCTMAssetOnL1(address)"(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    setCtmAssetHandlerAddressOnL1(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setCtmAssetHandlerAddressOnL1(address)"(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

  "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

  L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<string>;

  "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<string>;

  acceptOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "acceptOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  bridgeCheckCounterpartAddress(
    arg0: BigNumberish,
    arg1: BytesLike,
    _originalCaller: string,
    _assetHandlerAddressOnCounterpart: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)"(
    arg0: BigNumberish,
    arg1: BytesLike,
    _originalCaller: string,
    _assetHandlerAddressOnCounterpart: string,
    overrides?: CallOverrides
  ): Promise<void>;

  bridgehubConfirmL2Transaction(
    _chainId: BigNumberish,
    _txDataHash: BytesLike,
    _txHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
    _chainId: BigNumberish,
    _txDataHash: BytesLike,
    _txHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  bridgehubDeposit(
    _chainId: BigNumberish,
    _originalCaller: string,
    arg2: BigNumberish,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "bridgehubDeposit(uint256,address,uint256,bytes)"(
    _chainId: BigNumberish,
    _originalCaller: string,
    arg2: BigNumberish,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  calculateAssetId(_l1CTM: string, overrides?: CallOverrides): Promise<string>;

  "calculateAssetId(address)"(
    _l1CTM: string,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    _owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address)"(
    _owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  pendingOwner(overrides?: CallOverrides): Promise<string>;

  "pendingOwner()"(overrides?: CallOverrides): Promise<string>;

  registerCTMAssetOnL1(
    _ctmAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerCTMAssetOnL1(address)"(
    _ctmAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  setCtmAssetHandlerAddressOnL1(
    _ctmAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setCtmAssetHandlerAddressOnL1(address)"(
    _ctmAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<string>;

    "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<string>;

    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    "acceptOwnership()"(overrides?: CallOverrides): Promise<void>;

    bridgeCheckCounterpartAddress(
      arg0: BigNumberish,
      arg1: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<void>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _originalCaller: string,
      arg2: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      magicValue: string;
      l2Contract: string;
      l2Calldata: string;
      factoryDeps: string[];
      txDataHash: string;
      0: string;
      1: string;
      2: string;
      3: string[];
      4: string;
    }>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      arg2: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      magicValue: string;
      l2Contract: string;
      l2Calldata: string;
      factoryDeps: string[];
      txDataHash: string;
      0: string;
      1: string;
      2: string;
      3: string[];
      4: string;
    }>;

    calculateAssetId(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "calculateAssetId(address)"(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(_owner: string, overrides?: CallOverrides): Promise<void>;

    "initialize(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    pendingOwner(overrides?: CallOverrides): Promise<string>;

    "pendingOwner()"(overrides?: CallOverrides): Promise<string>;

    registerCTMAssetOnL1(
      _ctmAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerCTMAssetOnL1(address)"(
      _ctmAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    setCtmAssetHandlerAddressOnL1(
      _ctmAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setCtmAssetHandlerAddressOnL1(address)"(
      _ctmAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Initialized(version: null): EventFilter;

    OwnershipTransferStarted(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<BigNumber>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<BigNumber>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<BigNumber>;

    "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<BigNumber>;

    acceptOwnership(overrides?: Overrides): Promise<BigNumber>;

    "acceptOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    bridgeCheckCounterpartAddress(
      arg0: BigNumberish,
      arg1: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _originalCaller: string,
      arg2: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      arg2: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    calculateAssetId(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateAssetId(address)"(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(_owner: string, overrides?: Overrides): Promise<BigNumber>;

    "initialize(address)"(
      _owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    pendingOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "pendingOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    registerCTMAssetOnL1(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerCTMAssetOnL1(address)"(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    setCtmAssetHandlerAddressOnL1(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setCtmAssetHandlerAddressOnL1(address)"(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "L1_ASSET_ROUTER()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    acceptOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "acceptOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    bridgeCheckCounterpartAddress(
      arg0: BigNumberish,
      arg1: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)"(
      arg0: BigNumberish,
      arg1: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bridgehubConfirmL2Transaction(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "bridgehubConfirmL2Transaction(uint256,bytes32,bytes32)"(
      _chainId: BigNumberish,
      _txDataHash: BytesLike,
      _txHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _originalCaller: string,
      arg2: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      arg2: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    calculateAssetId(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calculateAssetId(address)"(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address)"(
      _owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "pendingOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerCTMAssetOnL1(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerCTMAssetOnL1(address)"(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    setCtmAssetHandlerAddressOnL1(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setCtmAssetHandlerAddressOnL1(address)"(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
