/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DummyL2InteropRootStorageInterface extends ethers.utils.Interface {
  functions: {
    "addInteropRoot(uint256,uint256,bytes32[])": FunctionFragment;
    "addThisChainInteropRoot(uint256,bytes32[])": FunctionFragment;
    "batchNumberFrominteropRoot(bytes32)": FunctionFragment;
    "chainIdFrominteropRoot(bytes32)": FunctionFragment;
    "interopRootSides(uint256,uint256,uint256)": FunctionFragment;
    "interopRoots(uint256,uint256)": FunctionFragment;
    "pendingMessageRootIds(uint256)": FunctionFragment;
    "pendingMessageRootIdsLength()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addInteropRoot",
    values: [BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addThisChainInteropRoot",
    values: [BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchNumberFrominteropRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "chainIdFrominteropRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "interopRootSides",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "interopRoots",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingMessageRootIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingMessageRootIdsLength",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addInteropRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addThisChainInteropRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchNumberFrominteropRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "chainIdFrominteropRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interopRootSides",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interopRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingMessageRootIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingMessageRootIdsLength",
    data: BytesLike
  ): Result;

  events: {
    "InteropRootAdded(uint256,uint256,bytes32[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "InteropRootAdded"): EventFragment;
}

export class DummyL2InteropRootStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DummyL2InteropRootStorageInterface;

  functions: {
    addInteropRoot(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addInteropRoot(uint256,uint256,bytes32[])"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addThisChainInteropRoot(
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addThisChainInteropRoot(uint256,bytes32[])"(
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    batchNumberFrominteropRoot(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      batchNumber: BigNumber;
      0: BigNumber;
    }>;

    "batchNumberFrominteropRoot(bytes32)"(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      batchNumber: BigNumber;
      0: BigNumber;
    }>;

    chainIdFrominteropRoot(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      chainId: BigNumber;
      0: BigNumber;
    }>;

    "chainIdFrominteropRoot(bytes32)"(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      chainId: BigNumber;
      0: BigNumber;
    }>;

    interopRootSides(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      interopRootSides: string;
      0: string;
    }>;

    "interopRootSides(uint256,uint256,uint256)"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      interopRootSides: string;
      0: string;
    }>;

    interopRoots(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      interopRoot: string;
      0: string;
    }>;

    "interopRoots(uint256,uint256)"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      interopRoot: string;
      0: string;
    }>;

    pendingMessageRootIds(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      chainId: BigNumber;
      batchNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "pendingMessageRootIds(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      chainId: BigNumber;
      batchNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    pendingMessageRootIdsLength(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "pendingMessageRootIdsLength()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;
  };

  addInteropRoot(
    chainId: BigNumberish,
    batchNumber: BigNumberish,
    sides: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addInteropRoot(uint256,uint256,bytes32[])"(
    chainId: BigNumberish,
    batchNumber: BigNumberish,
    sides: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addThisChainInteropRoot(
    batchNumber: BigNumberish,
    sides: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addThisChainInteropRoot(uint256,bytes32[])"(
    batchNumber: BigNumberish,
    sides: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  batchNumberFrominteropRoot(
    interopRoot: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "batchNumberFrominteropRoot(bytes32)"(
    interopRoot: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  chainIdFrominteropRoot(
    interopRoot: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "chainIdFrominteropRoot(bytes32)"(
    interopRoot: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  interopRootSides(
    chainId: BigNumberish,
    batchNumber: BigNumberish,
    arg2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "interopRootSides(uint256,uint256,uint256)"(
    chainId: BigNumberish,
    batchNumber: BigNumberish,
    arg2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  interopRoots(
    chainId: BigNumberish,
    batchNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "interopRoots(uint256,uint256)"(
    chainId: BigNumberish,
    batchNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  pendingMessageRootIds(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    chainId: BigNumber;
    batchNumber: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  "pendingMessageRootIds(uint256)"(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    chainId: BigNumber;
    batchNumber: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  pendingMessageRootIdsLength(overrides?: CallOverrides): Promise<BigNumber>;

  "pendingMessageRootIdsLength()"(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    addInteropRoot(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "addInteropRoot(uint256,uint256,bytes32[])"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    addThisChainInteropRoot(
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "addThisChainInteropRoot(uint256,bytes32[])"(
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchNumberFrominteropRoot(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "batchNumberFrominteropRoot(bytes32)"(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chainIdFrominteropRoot(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "chainIdFrominteropRoot(bytes32)"(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interopRootSides(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "interopRootSides(uint256,uint256,uint256)"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    interopRoots(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "interopRoots(uint256,uint256)"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    pendingMessageRootIds(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      chainId: BigNumber;
      batchNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "pendingMessageRootIds(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      chainId: BigNumber;
      batchNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    pendingMessageRootIdsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "pendingMessageRootIdsLength()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    InteropRootAdded(
      chainId: BigNumberish | null,
      batchNumber: BigNumberish | null,
      sides: null
    ): EventFilter;
  };

  estimateGas: {
    addInteropRoot(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addInteropRoot(uint256,uint256,bytes32[])"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    addThisChainInteropRoot(
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addThisChainInteropRoot(uint256,bytes32[])"(
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    batchNumberFrominteropRoot(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "batchNumberFrominteropRoot(bytes32)"(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chainIdFrominteropRoot(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "chainIdFrominteropRoot(bytes32)"(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interopRootSides(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "interopRootSides(uint256,uint256,uint256)"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interopRoots(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "interopRoots(uint256,uint256)"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingMessageRootIds(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pendingMessageRootIds(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingMessageRootIdsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "pendingMessageRootIdsLength()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addInteropRoot(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addInteropRoot(uint256,uint256,bytes32[])"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addThisChainInteropRoot(
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addThisChainInteropRoot(uint256,bytes32[])"(
      batchNumber: BigNumberish,
      sides: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    batchNumberFrominteropRoot(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "batchNumberFrominteropRoot(bytes32)"(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    chainIdFrominteropRoot(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "chainIdFrominteropRoot(bytes32)"(
      interopRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interopRootSides(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "interopRootSides(uint256,uint256,uint256)"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interopRoots(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "interopRoots(uint256,uint256)"(
      chainId: BigNumberish,
      batchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingMessageRootIds(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pendingMessageRootIds(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingMessageRootIdsLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pendingMessageRootIdsLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
