/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DummyEraBaseTokenBridgeInterface extends ethers.utils.Interface {
  functions: {
    "bridgehubDepositBaseToken(uint256,address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bridgehubDepositBaseToken",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "bridgehubDepositBaseToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class DummyEraBaseTokenBridge extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DummyEraBaseTokenBridgeInterface;

  functions: {
    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  bridgehubDepositBaseToken(
    _chainId: BigNumberish,
    _originalCaller: string,
    _l1Token: string,
    _amount: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
    _chainId: BigNumberish,
    _originalCaller: string,
    _l1Token: string,
    _amount: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bridgehubDepositBaseToken(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "bridgehubDepositBaseToken(uint256,address,address,uint256)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l1Token: string,
      _amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
