/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IAccessControlRestriction } from "./IAccessControlRestriction";

export class IAccessControlRestrictionFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAccessControlRestriction {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAccessControlRestriction;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "requiredRole",
        type: "bytes32",
      },
    ],
    name: "FallbackRoleSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes4",
        name: "selector",
        type: "bytes4",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "requiredRole",
        type: "bytes32",
      },
    ],
    name: "RoleSet",
    type: "event",
  },
];
