/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IAssetHandlerInterface extends ethers.utils.Interface {
  functions: {
    "bridgeBurn(uint256,uint256,bytes32,address,bytes)": FunctionFragment;
    "bridgeMint(uint256,bytes32,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bridgeBurn",
    values: [BigNumberish, BigNumberish, BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeMint",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "bridgeBurn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bridgeMint", data: BytesLike): Result;

  events: {
    "BridgeBurn(uint256,bytes32,address,address,uint256)": EventFragment;
    "BridgeMint(uint256,bytes32,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BridgeBurn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BridgeMint"): EventFragment;
}

export class IAssetHandler extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IAssetHandlerInterface;

  functions: {
    bridgeBurn(
      _chainId: BigNumberish,
      _msgValue: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "bridgeBurn(uint256,uint256,bytes32,address,bytes)"(
      _chainId: BigNumberish,
      _msgValue: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    bridgeMint(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "bridgeMint(uint256,bytes32,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  bridgeBurn(
    _chainId: BigNumberish,
    _msgValue: BigNumberish,
    _assetId: BytesLike,
    _originalCaller: string,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "bridgeBurn(uint256,uint256,bytes32,address,bytes)"(
    _chainId: BigNumberish,
    _msgValue: BigNumberish,
    _assetId: BytesLike,
    _originalCaller: string,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  bridgeMint(
    _chainId: BigNumberish,
    _assetId: BytesLike,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "bridgeMint(uint256,bytes32,bytes)"(
    _chainId: BigNumberish,
    _assetId: BytesLike,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    bridgeBurn(
      _chainId: BigNumberish,
      _msgValue: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "bridgeBurn(uint256,uint256,bytes32,address,bytes)"(
      _chainId: BigNumberish,
      _msgValue: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    bridgeMint(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "bridgeMint(uint256,bytes32,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    BridgeBurn(
      chainId: BigNumberish | null,
      assetId: BytesLike | null,
      sender: string | null,
      receiver: null,
      amount: null
    ): EventFilter;

    BridgeMint(
      chainId: BigNumberish | null,
      assetId: BytesLike | null,
      receiver: null,
      amount: null
    ): EventFilter;
  };

  estimateGas: {
    bridgeBurn(
      _chainId: BigNumberish,
      _msgValue: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "bridgeBurn(uint256,uint256,bytes32,address,bytes)"(
      _chainId: BigNumberish,
      _msgValue: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    bridgeMint(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "bridgeMint(uint256,bytes32,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bridgeBurn(
      _chainId: BigNumberish,
      _msgValue: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "bridgeBurn(uint256,uint256,bytes32,address,bytes)"(
      _chainId: BigNumberish,
      _msgValue: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    bridgeMint(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "bridgeMint(uint256,bytes32,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
