/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ICTMDeploymentTrackerInterface extends ethers.utils.Interface {
  functions: {
    "BRIDGE_HUB()": FunctionFragment;
    "L1_ASSET_ROUTER()": FunctionFragment;
    "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)": FunctionFragment;
    "bridgehubDeposit(uint256,address,uint256,bytes)": FunctionFragment;
    "calculateAssetId(address)": FunctionFragment;
    "registerCTMAssetOnL1(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BRIDGE_HUB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "L1_ASSET_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeCheckCounterpartAddress",
    values: [BigNumberish, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgehubDeposit",
    values: [BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateAssetId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCTMAssetOnL1",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "BRIDGE_HUB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "L1_ASSET_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgeCheckCounterpartAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgehubDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateAssetId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCTMAssetOnL1",
    data: BytesLike
  ): Result;

  events: {};
}

export class ICTMDeploymentTracker extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ICTMDeploymentTrackerInterface;

  functions: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    bridgeCheckCounterpartAddress(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    calculateAssetId(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "calculateAssetId(address)"(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    registerCTMAssetOnL1(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerCTMAssetOnL1(address)"(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

  "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

  L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<string>;

  "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<string>;

  bridgeCheckCounterpartAddress(
    _chainId: BigNumberish,
    _assetId: BytesLike,
    _originalCaller: string,
    _assetHandlerAddressOnCounterpart: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)"(
    _chainId: BigNumberish,
    _assetId: BytesLike,
    _originalCaller: string,
    _assetHandlerAddressOnCounterpart: string,
    overrides?: CallOverrides
  ): Promise<void>;

  bridgehubDeposit(
    _chainId: BigNumberish,
    _originalCaller: string,
    _l2Value: BigNumberish,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "bridgehubDeposit(uint256,address,uint256,bytes)"(
    _chainId: BigNumberish,
    _originalCaller: string,
    _l2Value: BigNumberish,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  calculateAssetId(_l1CTM: string, overrides?: CallOverrides): Promise<string>;

  "calculateAssetId(address)"(
    _l1CTM: string,
    overrides?: CallOverrides
  ): Promise<string>;

  registerCTMAssetOnL1(
    _ctmAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerCTMAssetOnL1(address)"(
    _ctmAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<string>;

    "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<string>;

    bridgeCheckCounterpartAddress(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<void>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      magicValue: string;
      l2Contract: string;
      l2Calldata: string;
      factoryDeps: string[];
      txDataHash: string;
      0: string;
      1: string;
      2: string;
      3: string[];
      4: string;
    }>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      magicValue: string;
      l2Contract: string;
      l2Calldata: string;
      factoryDeps: string[];
      txDataHash: string;
      0: string;
      1: string;
      2: string;
      3: string[];
      4: string;
    }>;

    calculateAssetId(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "calculateAssetId(address)"(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<string>;

    registerCTMAssetOnL1(
      _ctmAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerCTMAssetOnL1(address)"(
      _ctmAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<BigNumber>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<BigNumber>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<BigNumber>;

    "L1_ASSET_ROUTER()"(overrides?: CallOverrides): Promise<BigNumber>;

    bridgeCheckCounterpartAddress(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    calculateAssetId(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateAssetId(address)"(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerCTMAssetOnL1(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerCTMAssetOnL1(address)"(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    L1_ASSET_ROUTER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "L1_ASSET_ROUTER()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bridgeCheckCounterpartAddress(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bridgeCheckCounterpartAddress(uint256,bytes32,address,address)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _originalCaller: string,
      _assetHandlerAddressOnCounterpart: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bridgehubDeposit(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "bridgehubDeposit(uint256,address,uint256,bytes)"(
      _chainId: BigNumberish,
      _originalCaller: string,
      _l2Value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    calculateAssetId(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calculateAssetId(address)"(
      _l1CTM: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerCTMAssetOnL1(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerCTMAssetOnL1(address)"(
      _ctmAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
