/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IDiamondInitInterface extends ethers.utils.Interface {
  functions: {
    "initialize(tuple)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      {
        chainId: BigNumberish;
        bridgehub: string;
        chainTypeManager: string;
        protocolVersion: BigNumberish;
        admin: string;
        validatorTimelock: string;
        baseTokenAssetId: BytesLike;
        storedBatchZero: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l2BootloaderBytecodeHash: BytesLike;
        l2DefaultAccountBytecodeHash: BytesLike;
        l2EvmEmulatorBytecodeHash: BytesLike;
        priorityTxMaxGasLimit: BigNumberish;
        feeParams: {
          pubdataPricingMode: BigNumberish;
          batchOverheadL1Gas: BigNumberish;
          maxPubdataPerBatch: BigNumberish;
          maxL2GasPerBatch: BigNumberish;
          priorityTxMaxPubdata: BigNumberish;
          minimalL2GasPrice: BigNumberish;
        };
      }
    ]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;

  events: {};
}

export class IDiamondInit extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IDiamondInitInterface;

  functions: {
    initialize(
      _initData: {
        chainId: BigNumberish;
        bridgehub: string;
        chainTypeManager: string;
        protocolVersion: BigNumberish;
        admin: string;
        validatorTimelock: string;
        baseTokenAssetId: BytesLike;
        storedBatchZero: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l2BootloaderBytecodeHash: BytesLike;
        l2DefaultAccountBytecodeHash: BytesLike;
        l2EvmEmulatorBytecodeHash: BytesLike;
        priorityTxMaxGasLimit: BigNumberish;
        feeParams: {
          pubdataPricingMode: BigNumberish;
          batchOverheadL1Gas: BigNumberish;
          maxPubdataPerBatch: BigNumberish;
          maxL2GasPerBatch: BigNumberish;
          priorityTxMaxPubdata: BigNumberish;
          minimalL2GasPrice: BigNumberish;
        };
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize((uint256,address,address,uint256,address,address,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes32,bytes32,bytes32,uint256,(uint8,uint32,uint32,uint32,uint32,uint64)))"(
      _initData: {
        chainId: BigNumberish;
        bridgehub: string;
        chainTypeManager: string;
        protocolVersion: BigNumberish;
        admin: string;
        validatorTimelock: string;
        baseTokenAssetId: BytesLike;
        storedBatchZero: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l2BootloaderBytecodeHash: BytesLike;
        l2DefaultAccountBytecodeHash: BytesLike;
        l2EvmEmulatorBytecodeHash: BytesLike;
        priorityTxMaxGasLimit: BigNumberish;
        feeParams: {
          pubdataPricingMode: BigNumberish;
          batchOverheadL1Gas: BigNumberish;
          maxPubdataPerBatch: BigNumberish;
          maxL2GasPerBatch: BigNumberish;
          priorityTxMaxPubdata: BigNumberish;
          minimalL2GasPrice: BigNumberish;
        };
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  initialize(
    _initData: {
      chainId: BigNumberish;
      bridgehub: string;
      chainTypeManager: string;
      protocolVersion: BigNumberish;
      admin: string;
      validatorTimelock: string;
      baseTokenAssetId: BytesLike;
      storedBatchZero: BytesLike;
      verifier: string;
      verifierParams: {
        recursionNodeLevelVkHash: BytesLike;
        recursionLeafLevelVkHash: BytesLike;
        recursionCircuitsSetVksHash: BytesLike;
      };
      l2BootloaderBytecodeHash: BytesLike;
      l2DefaultAccountBytecodeHash: BytesLike;
      l2EvmEmulatorBytecodeHash: BytesLike;
      priorityTxMaxGasLimit: BigNumberish;
      feeParams: {
        pubdataPricingMode: BigNumberish;
        batchOverheadL1Gas: BigNumberish;
        maxPubdataPerBatch: BigNumberish;
        maxL2GasPerBatch: BigNumberish;
        priorityTxMaxPubdata: BigNumberish;
        minimalL2GasPrice: BigNumberish;
      };
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize((uint256,address,address,uint256,address,address,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes32,bytes32,bytes32,uint256,(uint8,uint32,uint32,uint32,uint32,uint64)))"(
    _initData: {
      chainId: BigNumberish;
      bridgehub: string;
      chainTypeManager: string;
      protocolVersion: BigNumberish;
      admin: string;
      validatorTimelock: string;
      baseTokenAssetId: BytesLike;
      storedBatchZero: BytesLike;
      verifier: string;
      verifierParams: {
        recursionNodeLevelVkHash: BytesLike;
        recursionLeafLevelVkHash: BytesLike;
        recursionCircuitsSetVksHash: BytesLike;
      };
      l2BootloaderBytecodeHash: BytesLike;
      l2DefaultAccountBytecodeHash: BytesLike;
      l2EvmEmulatorBytecodeHash: BytesLike;
      priorityTxMaxGasLimit: BigNumberish;
      feeParams: {
        pubdataPricingMode: BigNumberish;
        batchOverheadL1Gas: BigNumberish;
        maxPubdataPerBatch: BigNumberish;
        maxL2GasPerBatch: BigNumberish;
        priorityTxMaxPubdata: BigNumberish;
        minimalL2GasPrice: BigNumberish;
      };
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    initialize(
      _initData: {
        chainId: BigNumberish;
        bridgehub: string;
        chainTypeManager: string;
        protocolVersion: BigNumberish;
        admin: string;
        validatorTimelock: string;
        baseTokenAssetId: BytesLike;
        storedBatchZero: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l2BootloaderBytecodeHash: BytesLike;
        l2DefaultAccountBytecodeHash: BytesLike;
        l2EvmEmulatorBytecodeHash: BytesLike;
        priorityTxMaxGasLimit: BigNumberish;
        feeParams: {
          pubdataPricingMode: BigNumberish;
          batchOverheadL1Gas: BigNumberish;
          maxPubdataPerBatch: BigNumberish;
          maxL2GasPerBatch: BigNumberish;
          priorityTxMaxPubdata: BigNumberish;
          minimalL2GasPrice: BigNumberish;
        };
      },
      overrides?: CallOverrides
    ): Promise<string>;

    "initialize((uint256,address,address,uint256,address,address,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes32,bytes32,bytes32,uint256,(uint8,uint32,uint32,uint32,uint32,uint64)))"(
      _initData: {
        chainId: BigNumberish;
        bridgehub: string;
        chainTypeManager: string;
        protocolVersion: BigNumberish;
        admin: string;
        validatorTimelock: string;
        baseTokenAssetId: BytesLike;
        storedBatchZero: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l2BootloaderBytecodeHash: BytesLike;
        l2DefaultAccountBytecodeHash: BytesLike;
        l2EvmEmulatorBytecodeHash: BytesLike;
        priorityTxMaxGasLimit: BigNumberish;
        feeParams: {
          pubdataPricingMode: BigNumberish;
          batchOverheadL1Gas: BigNumberish;
          maxPubdataPerBatch: BigNumberish;
          maxL2GasPerBatch: BigNumberish;
          priorityTxMaxPubdata: BigNumberish;
          minimalL2GasPrice: BigNumberish;
        };
      },
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    initialize(
      _initData: {
        chainId: BigNumberish;
        bridgehub: string;
        chainTypeManager: string;
        protocolVersion: BigNumberish;
        admin: string;
        validatorTimelock: string;
        baseTokenAssetId: BytesLike;
        storedBatchZero: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l2BootloaderBytecodeHash: BytesLike;
        l2DefaultAccountBytecodeHash: BytesLike;
        l2EvmEmulatorBytecodeHash: BytesLike;
        priorityTxMaxGasLimit: BigNumberish;
        feeParams: {
          pubdataPricingMode: BigNumberish;
          batchOverheadL1Gas: BigNumberish;
          maxPubdataPerBatch: BigNumberish;
          maxL2GasPerBatch: BigNumberish;
          priorityTxMaxPubdata: BigNumberish;
          minimalL2GasPrice: BigNumberish;
        };
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize((uint256,address,address,uint256,address,address,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes32,bytes32,bytes32,uint256,(uint8,uint32,uint32,uint32,uint32,uint64)))"(
      _initData: {
        chainId: BigNumberish;
        bridgehub: string;
        chainTypeManager: string;
        protocolVersion: BigNumberish;
        admin: string;
        validatorTimelock: string;
        baseTokenAssetId: BytesLike;
        storedBatchZero: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l2BootloaderBytecodeHash: BytesLike;
        l2DefaultAccountBytecodeHash: BytesLike;
        l2EvmEmulatorBytecodeHash: BytesLike;
        priorityTxMaxGasLimit: BigNumberish;
        feeParams: {
          pubdataPricingMode: BigNumberish;
          batchOverheadL1Gas: BigNumberish;
          maxPubdataPerBatch: BigNumberish;
          maxL2GasPerBatch: BigNumberish;
          priorityTxMaxPubdata: BigNumberish;
          minimalL2GasPrice: BigNumberish;
        };
      },
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      _initData: {
        chainId: BigNumberish;
        bridgehub: string;
        chainTypeManager: string;
        protocolVersion: BigNumberish;
        admin: string;
        validatorTimelock: string;
        baseTokenAssetId: BytesLike;
        storedBatchZero: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l2BootloaderBytecodeHash: BytesLike;
        l2DefaultAccountBytecodeHash: BytesLike;
        l2EvmEmulatorBytecodeHash: BytesLike;
        priorityTxMaxGasLimit: BigNumberish;
        feeParams: {
          pubdataPricingMode: BigNumberish;
          batchOverheadL1Gas: BigNumberish;
          maxPubdataPerBatch: BigNumberish;
          maxL2GasPerBatch: BigNumberish;
          priorityTxMaxPubdata: BigNumberish;
          minimalL2GasPrice: BigNumberish;
        };
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize((uint256,address,address,uint256,address,address,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes32,bytes32,bytes32,uint256,(uint8,uint32,uint32,uint32,uint32,uint64)))"(
      _initData: {
        chainId: BigNumberish;
        bridgehub: string;
        chainTypeManager: string;
        protocolVersion: BigNumberish;
        admin: string;
        validatorTimelock: string;
        baseTokenAssetId: BytesLike;
        storedBatchZero: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l2BootloaderBytecodeHash: BytesLike;
        l2DefaultAccountBytecodeHash: BytesLike;
        l2EvmEmulatorBytecodeHash: BytesLike;
        priorityTxMaxGasLimit: BigNumberish;
        feeParams: {
          pubdataPricingMode: BigNumberish;
          batchOverheadL1Gas: BigNumberish;
          maxPubdataPerBatch: BigNumberish;
          maxL2GasPerBatch: BigNumberish;
          priorityTxMaxPubdata: BigNumberish;
          minimalL2GasPrice: BigNumberish;
        };
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
