/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IGatewayUpgradeInterface extends ethers.utils.Interface {
  functions: {
    "upgradeExternal(tuple)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "upgradeExternal",
    values: [
      {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "upgradeExternal",
    data: BytesLike
  ): Result;

  events: {};
}

export class IGatewayUpgrade extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IGatewayUpgradeInterface;

  functions: {
    upgradeExternal(
      _upgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "upgradeExternal(((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,uint256[],bytes,bytes),bytes32,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes,bytes,uint256,uint256))"(
      _upgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  upgradeExternal(
    _upgrade: {
      l2ProtocolUpgradeTx: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BigNumberish[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      };
      bootloaderHash: BytesLike;
      defaultAccountHash: BytesLike;
      evmEmulatorHash: BytesLike;
      verifier: string;
      verifierParams: {
        recursionNodeLevelVkHash: BytesLike;
        recursionLeafLevelVkHash: BytesLike;
        recursionCircuitsSetVksHash: BytesLike;
      };
      l1ContractsUpgradeCalldata: BytesLike;
      postUpgradeCalldata: BytesLike;
      upgradeTimestamp: BigNumberish;
      newProtocolVersion: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "upgradeExternal(((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,uint256[],bytes,bytes),bytes32,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes,bytes,uint256,uint256))"(
    _upgrade: {
      l2ProtocolUpgradeTx: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BigNumberish[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      };
      bootloaderHash: BytesLike;
      defaultAccountHash: BytesLike;
      evmEmulatorHash: BytesLike;
      verifier: string;
      verifierParams: {
        recursionNodeLevelVkHash: BytesLike;
        recursionLeafLevelVkHash: BytesLike;
        recursionCircuitsSetVksHash: BytesLike;
      };
      l1ContractsUpgradeCalldata: BytesLike;
      postUpgradeCalldata: BytesLike;
      upgradeTimestamp: BigNumberish;
      newProtocolVersion: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    upgradeExternal(
      _upgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "upgradeExternal(((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,uint256[],bytes,bytes),bytes32,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes,bytes,uint256,uint256))"(
      _upgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    upgradeExternal(
      _upgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "upgradeExternal(((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,uint256[],bytes,bytes),bytes32,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes,bytes,uint256,uint256))"(
      _upgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    upgradeExternal(
      _upgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "upgradeExternal(((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,uint256[],bytes,bytes),bytes32,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes,bytes,uint256,uint256))"(
      _upgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
