/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IL1AssetHandlerInterface extends ethers.utils.Interface {
  functions: {
    "bridgeRecoverFailedTransfer(uint256,bytes32,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bridgeRecoverFailedTransfer",
    values: [BigNumberish, BytesLike, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "bridgeRecoverFailedTransfer",
    data: BytesLike
  ): Result;

  events: {};
}

export class IL1AssetHandler extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IL1AssetHandlerInterface;

  functions: {
    bridgeRecoverFailedTransfer(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _depositSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "bridgeRecoverFailedTransfer(uint256,bytes32,address,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _depositSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  bridgeRecoverFailedTransfer(
    _chainId: BigNumberish,
    _assetId: BytesLike,
    _depositSender: string,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "bridgeRecoverFailedTransfer(uint256,bytes32,address,bytes)"(
    _chainId: BigNumberish,
    _assetId: BytesLike,
    _depositSender: string,
    _data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    bridgeRecoverFailedTransfer(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _depositSender: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "bridgeRecoverFailedTransfer(uint256,bytes32,address,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _depositSender: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    bridgeRecoverFailedTransfer(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _depositSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "bridgeRecoverFailedTransfer(uint256,bytes32,address,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _depositSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bridgeRecoverFailedTransfer(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _depositSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "bridgeRecoverFailedTransfer(uint256,bytes32,address,bytes)"(
      _chainId: BigNumberish,
      _assetId: BytesLike,
      _depositSender: string,
      _data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
