/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IL1BaseTokenAssetHandlerInterface extends ethers.utils.Interface {
  functions: {
    "tokenAddress(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "tokenAddress",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "tokenAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export class IL1BaseTokenAssetHandler extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IL1BaseTokenAssetHandlerInterface;

  functions: {
    tokenAddress(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "tokenAddress(bytes32)"(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  tokenAddress(_assetId: BytesLike, overrides?: CallOverrides): Promise<string>;

  "tokenAddress(bytes32)"(
    _assetId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    tokenAddress(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "tokenAddress(bytes32)"(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    tokenAddress(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenAddress(bytes32)"(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    tokenAddress(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenAddress(bytes32)"(
      _assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
