/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IL1GenesisUpgrade } from "./IL1GenesisUpgrade";

export class IL1GenesisUpgradeFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL1GenesisUpgrade {
    return new Contract(address, _abi, signerOrProvider) as IL1GenesisUpgrade;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_zkChain",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "txType",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "from",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "to",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "gasLimit",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "gasPerPubdataByteLimit",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxFeePerGas",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxPriorityFeePerGas",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "paymaster",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "uint256[4]",
            name: "reserved",
            type: "uint256[4]",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
          {
            internalType: "uint256[]",
            name: "factoryDeps",
            type: "uint256[]",
          },
          {
            internalType: "bytes",
            name: "paymasterInput",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "reservedDynamic",
            type: "bytes",
          },
        ],
        indexed: false,
        internalType: "struct L2CanonicalTransaction",
        name: "_l2Transaction",
        type: "tuple",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_protocolVersion",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes[]",
        name: "_factoryDeps",
        type: "bytes[]",
      },
    ],
    name: "GenesisUpgrade",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_l1GenesisUpgrade",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_chainId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_protocolVersion",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_l1CtmDeployerAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_forceDeployments",
        type: "bytes",
      },
      {
        internalType: "bytes[]",
        name: "_factoryDeps",
        type: "bytes[]",
      },
    ],
    name: "genesisUpgrade",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
