/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IL2GatewayUpgrade } from "./IL2GatewayUpgrade";

export class IL2GatewayUpgradeFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL2GatewayUpgrade {
    return new Contract(address, _abi, signerOrProvider) as IL2GatewayUpgrade;
  }
}

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "bytecodeHash",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "newAddress",
            type: "address",
          },
          {
            internalType: "bool",
            name: "callConstructor",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "input",
            type: "bytes",
          },
        ],
        internalType: "struct IL2ContractDeployer.ForceDeployment[]",
        name: "_forceDeployments",
        type: "tuple[]",
      },
      {
        internalType: "address",
        name: "_ctmDeployer",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_fixedForceDeploymentsData",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_additionalForceDeploymentsData",
        type: "bytes",
      },
    ],
    name: "upgrade",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
