/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IL2GatewayUpgradeInterface extends ethers.utils.Interface {
  functions: {
    "upgrade(tuple[],address,bytes,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "upgrade",
    values: [
      {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      string,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;

  events: {};
}

export class IL2GatewayUpgrade extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IL2GatewayUpgradeInterface;

  functions: {
    upgrade(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      _ctmDeployer: string,
      _fixedForceDeploymentsData: BytesLike,
      _additionalForceDeploymentsData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "upgrade(tuple[],address,bytes,bytes)"(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      _ctmDeployer: string,
      _fixedForceDeploymentsData: BytesLike,
      _additionalForceDeploymentsData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  upgrade(
    _forceDeployments: {
      bytecodeHash: BytesLike;
      newAddress: string;
      callConstructor: boolean;
      value: BigNumberish;
      input: BytesLike;
    }[],
    _ctmDeployer: string,
    _fixedForceDeploymentsData: BytesLike,
    _additionalForceDeploymentsData: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "upgrade(tuple[],address,bytes,bytes)"(
    _forceDeployments: {
      bytecodeHash: BytesLike;
      newAddress: string;
      callConstructor: boolean;
      value: BigNumberish;
      input: BytesLike;
    }[],
    _ctmDeployer: string,
    _fixedForceDeploymentsData: BytesLike,
    _additionalForceDeploymentsData: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    upgrade(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      _ctmDeployer: string,
      _fixedForceDeploymentsData: BytesLike,
      _additionalForceDeploymentsData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgrade(tuple[],address,bytes,bytes)"(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      _ctmDeployer: string,
      _fixedForceDeploymentsData: BytesLike,
      _additionalForceDeploymentsData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    upgrade(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      _ctmDeployer: string,
      _fixedForceDeploymentsData: BytesLike,
      _additionalForceDeploymentsData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "upgrade(tuple[],address,bytes,bytes)"(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      _ctmDeployer: string,
      _fixedForceDeploymentsData: BytesLike,
      _additionalForceDeploymentsData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    upgrade(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      _ctmDeployer: string,
      _fixedForceDeploymentsData: BytesLike,
      _additionalForceDeploymentsData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "upgrade(tuple[],address,bytes,bytes)"(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      _ctmDeployer: string,
      _fixedForceDeploymentsData: BytesLike,
      _additionalForceDeploymentsData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
