/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IL2InteropRootStorage } from "./IL2InteropRootStorage";

export class IL2InteropRootStorageFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL2InteropRootStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IL2InteropRootStorage;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "blockOrBatchNumber",
        type: "uint256",
      },
    ],
    name: "interopRoots",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
