/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPermanentRestriction } from "./IPermanentRestriction";

export class IPermanentRestrictionFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPermanentRestriction {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPermanentRestriction;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "implementationHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isAllowed",
        type: "bool",
      },
    ],
    name: "AdminImplementationAllowed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "adminAddress",
        type: "address",
      },
    ],
    name: "AllowL2Admin",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isAllowed",
        type: "bool",
      },
    ],
    name: "AllowedDataChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes4",
        name: "selector",
        type: "bytes4",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isValidated",
        type: "bool",
      },
    ],
    name: "SelectorValidationChanged",
    type: "event",
  },
];
