/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IRestriction } from "./IRestriction";

export class IRestrictionFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRestriction {
    return new Contract(address, _abi, signerOrProvider) as IRestriction;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getSupportsRestrictionMagic",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "target",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct Call",
        name: "_call",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "_invoker",
        type: "address",
      },
    ],
    name: "validateCall",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
];
