/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ISystemContextInterface extends ethers.utils.Interface {
  functions: {
    "setChainId(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "setChainId",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "setChainId", data: BytesLike): Result;

  events: {};
}

export class ISystemContext extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ISystemContextInterface;

  functions: {
    setChainId(
      _newChainId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setChainId(uint256)"(
      _newChainId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  setChainId(
    _newChainId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setChainId(uint256)"(
    _newChainId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    setChainId(
      _newChainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setChainId(uint256)"(
      _newChainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    setChainId(
      _newChainId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setChainId(uint256)"(
      _newChainId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setChainId(
      _newChainId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setChainId(uint256)"(
      _newChainId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
