/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IValidatorTimelockInterface extends ethers.utils.Interface {
  functions: {
    "BRIDGE_HUB()": FunctionFragment;
    "COMMITTER_ROLE()": FunctionFragment;
    "EXECUTOR_ROLE()": FunctionFragment;
    "OPTIONAL_COMMITTER_ADMIN_ROLE()": FunctionFragment;
    "OPTIONAL_EXECUTOR_ADMIN_ROLE()": FunctionFragment;
    "OPTIONAL_PRECOMMITTER_ADMIN_ROLE()": FunctionFragment;
    "OPTIONAL_PROVER_ADMIN_ROLE()": FunctionFragment;
    "OPTIONAL_REVERTER_ADMIN_ROLE()": FunctionFragment;
    "PRECOMMITTER_ROLE()": FunctionFragment;
    "PROVER_ROLE()": FunctionFragment;
    "REVERTER_ROLE()": FunctionFragment;
    "addValidator(address,address)": FunctionFragment;
    "addValidatorForChainId(uint256,address)": FunctionFragment;
    "addValidatorRoles(address,address,tuple)": FunctionFragment;
    "commitBatchesSharedBridge(address,uint256,uint256,bytes)": FunctionFragment;
    "executeBatchesSharedBridge(address,uint256,uint256,bytes)": FunctionFragment;
    "executionDelay()": FunctionFragment;
    "getCommittedBatchTimestamp(address,uint256)": FunctionFragment;
    "getName()": FunctionFragment;
    "hasRoleForChainId(uint256,bytes32,address)": FunctionFragment;
    "initialize(address,uint32)": FunctionFragment;
    "precommitSharedBridge(address,uint256,bytes)": FunctionFragment;
    "proveBatchesSharedBridge(address,uint256,uint256,bytes)": FunctionFragment;
    "removeValidator(address,address)": FunctionFragment;
    "removeValidatorForChainId(uint256,address)": FunctionFragment;
    "removeValidatorRoles(address,address,tuple)": FunctionFragment;
    "revertBatchesSharedBridge(address,uint256)": FunctionFragment;
    "setExecutionDelay(uint32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BRIDGE_HUB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COMMITTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPTIONAL_COMMITTER_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPTIONAL_EXECUTOR_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPTIONAL_PRECOMMITTER_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPTIONAL_PROVER_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPTIONAL_REVERTER_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRECOMMITTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROVER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REVERTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addValidator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addValidatorForChainId",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addValidatorRoles",
    values: [
      string,
      string,
      {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "commitBatchesSharedBridge",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatchesSharedBridge",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executionDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCommittedBatchTimestamp",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasRoleForChainId",
    values: [BigNumberish, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "precommitSharedBridge",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proveBatchesSharedBridge",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeValidator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeValidatorForChainId",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeValidatorRoles",
    values: [
      string,
      string,
      {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revertBatchesSharedBridge",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutionDelay",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "BRIDGE_HUB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "COMMITTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPTIONAL_COMMITTER_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPTIONAL_EXECUTOR_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPTIONAL_PRECOMMITTER_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPTIONAL_PROVER_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPTIONAL_REVERTER_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRECOMMITTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROVER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REVERTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addValidatorForChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addValidatorRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitBatchesSharedBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBatchesSharedBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommittedBatchTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasRoleForChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "precommitSharedBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proveBatchesSharedBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeValidatorForChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeValidatorRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertBatchesSharedBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecutionDelay",
    data: BytesLike
  ): Result;

  events: {
    "BatchPrecommitmentSet(uint256,uint256,bytes32)": EventFragment;
    "BlockCommit(uint256,bytes32,bytes32)": EventFragment;
    "BlockExecution(uint256,bytes32,bytes32)": EventFragment;
    "BlocksRevert(uint256,uint256,uint256)": EventFragment;
    "BlocksVerification(uint256,uint256)": EventFragment;
    "NewExecutionDelay(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BatchPrecommitmentSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlockCommit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlockExecution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlocksRevert"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlocksVerification"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewExecutionDelay"): EventFragment;
}

export class IValidatorTimelock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IValidatorTimelockInterface;

  functions: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    COMMITTER_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "COMMITTER_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    EXECUTOR_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "EXECUTOR_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    OPTIONAL_COMMITTER_ADMIN_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "OPTIONAL_COMMITTER_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    OPTIONAL_EXECUTOR_ADMIN_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "OPTIONAL_EXECUTOR_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    OPTIONAL_PRECOMMITTER_ADMIN_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "OPTIONAL_PRECOMMITTER_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    OPTIONAL_PROVER_ADMIN_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "OPTIONAL_PROVER_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    OPTIONAL_REVERTER_ADMIN_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "OPTIONAL_REVERTER_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    PRECOMMITTER_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "PRECOMMITTER_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    PROVER_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "PROVER_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    REVERTER_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "REVERTER_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    addValidator(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addValidator(address,address)"(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addValidatorForChainId(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addValidatorForChainId(uint256,address)"(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addValidatorRoles(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addValidatorRoles(address,address,(bool,bool,bool,bool,bool))"(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    commitBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "commitBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    executeBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    executionDelay(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    "executionDelay()"(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    getCommittedBatchTimestamp(
      _chainAddress: string,
      _l2BatchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getCommittedBatchTimestamp(address,uint256)"(
      _chainAddress: string,
      _l2BatchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getName(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "getName()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    hasRoleForChainId(
      _chainId: BigNumberish,
      _role: BytesLike,
      _address: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "hasRoleForChainId(uint256,bytes32,address)"(
      _chainId: BigNumberish,
      _role: BytesLike,
      _address: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    initialize(
      _initialOwner: string,
      _initialExecutionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,uint32)"(
      _initialOwner: string,
      _initialExecutionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    precommitSharedBridge(
      _chainAddress: string,
      _l2BlockNumber: BigNumberish,
      _l2Block: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "precommitSharedBridge(address,uint256,bytes)"(
      _chainAddress: string,
      _l2BlockNumber: BigNumberish,
      _l2Block: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    proveBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _proofData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "proveBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _proofData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    removeValidator(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeValidator(address,address)"(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    removeValidatorForChainId(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeValidatorForChainId(uint256,address)"(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    removeValidatorRoles(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeValidatorRoles(address,address,(bool,bool,bool,bool,bool))"(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    revertBatchesSharedBridge(
      _chainAddress: string,
      _newLastBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revertBatchesSharedBridge(address,uint256)"(
      _chainAddress: string,
      _newLastBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setExecutionDelay(
      _executionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setExecutionDelay(uint32)"(
      _executionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

  "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

  COMMITTER_ROLE(overrides?: CallOverrides): Promise<string>;

  "COMMITTER_ROLE()"(overrides?: CallOverrides): Promise<string>;

  EXECUTOR_ROLE(overrides?: CallOverrides): Promise<string>;

  "EXECUTOR_ROLE()"(overrides?: CallOverrides): Promise<string>;

  OPTIONAL_COMMITTER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "OPTIONAL_COMMITTER_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  OPTIONAL_EXECUTOR_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "OPTIONAL_EXECUTOR_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  OPTIONAL_PRECOMMITTER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "OPTIONAL_PRECOMMITTER_ADMIN_ROLE()"(
    overrides?: CallOverrides
  ): Promise<string>;

  OPTIONAL_PROVER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "OPTIONAL_PROVER_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  OPTIONAL_REVERTER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "OPTIONAL_REVERTER_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  PRECOMMITTER_ROLE(overrides?: CallOverrides): Promise<string>;

  "PRECOMMITTER_ROLE()"(overrides?: CallOverrides): Promise<string>;

  PROVER_ROLE(overrides?: CallOverrides): Promise<string>;

  "PROVER_ROLE()"(overrides?: CallOverrides): Promise<string>;

  REVERTER_ROLE(overrides?: CallOverrides): Promise<string>;

  "REVERTER_ROLE()"(overrides?: CallOverrides): Promise<string>;

  addValidator(
    _chainAddress: string,
    _validator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addValidator(address,address)"(
    _chainAddress: string,
    _validator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addValidatorForChainId(
    _chainId: BigNumberish,
    _validator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addValidatorForChainId(uint256,address)"(
    _chainId: BigNumberish,
    _validator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addValidatorRoles(
    _chainAddress: string,
    _validator: string,
    params: {
      rotatePrecommitterRole: boolean;
      rotateCommitterRole: boolean;
      rotateReverterRole: boolean;
      rotateProverRole: boolean;
      rotateExecutorRole: boolean;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addValidatorRoles(address,address,(bool,bool,bool,bool,bool))"(
    _chainAddress: string,
    _validator: string,
    params: {
      rotatePrecommitterRole: boolean;
      rotateCommitterRole: boolean;
      rotateReverterRole: boolean;
      rotateProverRole: boolean;
      rotateExecutorRole: boolean;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  commitBatchesSharedBridge(
    _chainAddress: string,
    _processBatchFrom: BigNumberish,
    _processBatchTo: BigNumberish,
    _batchData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "commitBatchesSharedBridge(address,uint256,uint256,bytes)"(
    _chainAddress: string,
    _processBatchFrom: BigNumberish,
    _processBatchTo: BigNumberish,
    _batchData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  executeBatchesSharedBridge(
    _chainAddress: string,
    _processBatchFrom: BigNumberish,
    _processBatchTo: BigNumberish,
    _batchData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeBatchesSharedBridge(address,uint256,uint256,bytes)"(
    _chainAddress: string,
    _processBatchFrom: BigNumberish,
    _processBatchTo: BigNumberish,
    _batchData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  executionDelay(overrides?: CallOverrides): Promise<number>;

  "executionDelay()"(overrides?: CallOverrides): Promise<number>;

  getCommittedBatchTimestamp(
    _chainAddress: string,
    _l2BatchNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getCommittedBatchTimestamp(address,uint256)"(
    _chainAddress: string,
    _l2BatchNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getName(overrides?: CallOverrides): Promise<string>;

  "getName()"(overrides?: CallOverrides): Promise<string>;

  hasRoleForChainId(
    _chainId: BigNumberish,
    _role: BytesLike,
    _address: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasRoleForChainId(uint256,bytes32,address)"(
    _chainId: BigNumberish,
    _role: BytesLike,
    _address: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    _initialOwner: string,
    _initialExecutionDelay: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,uint32)"(
    _initialOwner: string,
    _initialExecutionDelay: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  precommitSharedBridge(
    _chainAddress: string,
    _l2BlockNumber: BigNumberish,
    _l2Block: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "precommitSharedBridge(address,uint256,bytes)"(
    _chainAddress: string,
    _l2BlockNumber: BigNumberish,
    _l2Block: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  proveBatchesSharedBridge(
    _chainAddress: string,
    _processBatchFrom: BigNumberish,
    _processBatchTo: BigNumberish,
    _proofData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "proveBatchesSharedBridge(address,uint256,uint256,bytes)"(
    _chainAddress: string,
    _processBatchFrom: BigNumberish,
    _processBatchTo: BigNumberish,
    _proofData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  removeValidator(
    _chainAddress: string,
    _validator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeValidator(address,address)"(
    _chainAddress: string,
    _validator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  removeValidatorForChainId(
    _chainId: BigNumberish,
    _validator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeValidatorForChainId(uint256,address)"(
    _chainId: BigNumberish,
    _validator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  removeValidatorRoles(
    _chainAddress: string,
    _validator: string,
    params: {
      rotatePrecommitterRole: boolean;
      rotateCommitterRole: boolean;
      rotateReverterRole: boolean;
      rotateProverRole: boolean;
      rotateExecutorRole: boolean;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeValidatorRoles(address,address,(bool,bool,bool,bool,bool))"(
    _chainAddress: string,
    _validator: string,
    params: {
      rotatePrecommitterRole: boolean;
      rotateCommitterRole: boolean;
      rotateReverterRole: boolean;
      rotateProverRole: boolean;
      rotateExecutorRole: boolean;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  revertBatchesSharedBridge(
    _chainAddress: string,
    _newLastBatch: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revertBatchesSharedBridge(address,uint256)"(
    _chainAddress: string,
    _newLastBatch: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setExecutionDelay(
    _executionDelay: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setExecutionDelay(uint32)"(
    _executionDelay: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

    COMMITTER_ROLE(overrides?: CallOverrides): Promise<string>;

    "COMMITTER_ROLE()"(overrides?: CallOverrides): Promise<string>;

    EXECUTOR_ROLE(overrides?: CallOverrides): Promise<string>;

    "EXECUTOR_ROLE()"(overrides?: CallOverrides): Promise<string>;

    OPTIONAL_COMMITTER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "OPTIONAL_COMMITTER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<string>;

    OPTIONAL_EXECUTOR_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "OPTIONAL_EXECUTOR_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<string>;

    OPTIONAL_PRECOMMITTER_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<string>;

    "OPTIONAL_PRECOMMITTER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<string>;

    OPTIONAL_PROVER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "OPTIONAL_PROVER_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

    OPTIONAL_REVERTER_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "OPTIONAL_REVERTER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<string>;

    PRECOMMITTER_ROLE(overrides?: CallOverrides): Promise<string>;

    "PRECOMMITTER_ROLE()"(overrides?: CallOverrides): Promise<string>;

    PROVER_ROLE(overrides?: CallOverrides): Promise<string>;

    "PROVER_ROLE()"(overrides?: CallOverrides): Promise<string>;

    REVERTER_ROLE(overrides?: CallOverrides): Promise<string>;

    "REVERTER_ROLE()"(overrides?: CallOverrides): Promise<string>;

    addValidator(
      _chainAddress: string,
      _validator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addValidator(address,address)"(
      _chainAddress: string,
      _validator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addValidatorForChainId(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addValidatorForChainId(uint256,address)"(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addValidatorRoles(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "addValidatorRoles(address,address,(bool,bool,bool,bool,bool))"(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    commitBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "commitBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    executeBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    executionDelay(overrides?: CallOverrides): Promise<number>;

    "executionDelay()"(overrides?: CallOverrides): Promise<number>;

    getCommittedBatchTimestamp(
      _chainAddress: string,
      _l2BatchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCommittedBatchTimestamp(address,uint256)"(
      _chainAddress: string,
      _l2BatchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getName(overrides?: CallOverrides): Promise<string>;

    "getName()"(overrides?: CallOverrides): Promise<string>;

    hasRoleForChainId(
      _chainId: BigNumberish,
      _role: BytesLike,
      _address: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasRoleForChainId(uint256,bytes32,address)"(
      _chainId: BigNumberish,
      _role: BytesLike,
      _address: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      _initialOwner: string,
      _initialExecutionDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,uint32)"(
      _initialOwner: string,
      _initialExecutionDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    precommitSharedBridge(
      _chainAddress: string,
      _l2BlockNumber: BigNumberish,
      _l2Block: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "precommitSharedBridge(address,uint256,bytes)"(
      _chainAddress: string,
      _l2BlockNumber: BigNumberish,
      _l2Block: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    proveBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _proofData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "proveBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _proofData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    removeValidator(
      _chainAddress: string,
      _validator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeValidator(address,address)"(
      _chainAddress: string,
      _validator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    removeValidatorForChainId(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeValidatorForChainId(uint256,address)"(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    removeValidatorRoles(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "removeValidatorRoles(address,address,(bool,bool,bool,bool,bool))"(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    revertBatchesSharedBridge(
      _chainAddress: string,
      _newLastBatch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "revertBatchesSharedBridge(address,uint256)"(
      _chainAddress: string,
      _newLastBatch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setExecutionDelay(
      _executionDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setExecutionDelay(uint32)"(
      _executionDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    BatchPrecommitmentSet(
      batchNumber: BigNumberish | null,
      untrustedLastL2BlockNumberHint: BigNumberish | null,
      precommitment: null
    ): EventFilter;

    BlockCommit(
      batchNumber: BigNumberish | null,
      batchHash: BytesLike | null,
      commitment: BytesLike | null
    ): EventFilter;

    BlockExecution(
      batchNumber: BigNumberish | null,
      batchHash: BytesLike | null,
      commitment: BytesLike | null
    ): EventFilter;

    BlocksRevert(
      totalBatchesCommitted: null,
      totalBatchesVerified: null,
      totalBatchesExecuted: null
    ): EventFilter;

    BlocksVerification(
      previousLastVerifiedBatch: BigNumberish | null,
      currentLastVerifiedBatch: BigNumberish | null
    ): EventFilter;

    NewExecutionDelay(_newExecutionDelay: null): EventFilter;
  };

  estimateGas: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<BigNumber>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<BigNumber>;

    COMMITTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "COMMITTER_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    EXECUTOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "EXECUTOR_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    OPTIONAL_COMMITTER_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "OPTIONAL_COMMITTER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    OPTIONAL_EXECUTOR_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "OPTIONAL_EXECUTOR_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    OPTIONAL_PRECOMMITTER_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "OPTIONAL_PRECOMMITTER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    OPTIONAL_PROVER_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "OPTIONAL_PROVER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    OPTIONAL_REVERTER_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "OPTIONAL_REVERTER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PRECOMMITTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "PRECOMMITTER_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    PROVER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "PROVER_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    REVERTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "REVERTER_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    addValidator(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addValidator(address,address)"(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addValidatorForChainId(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addValidatorForChainId(uint256,address)"(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addValidatorRoles(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addValidatorRoles(address,address,(bool,bool,bool,bool,bool))"(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    commitBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "commitBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    executeBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    executionDelay(overrides?: CallOverrides): Promise<BigNumber>;

    "executionDelay()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCommittedBatchTimestamp(
      _chainAddress: string,
      _l2BatchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCommittedBatchTimestamp(address,uint256)"(
      _chainAddress: string,
      _l2BatchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getName(overrides?: CallOverrides): Promise<BigNumber>;

    "getName()"(overrides?: CallOverrides): Promise<BigNumber>;

    hasRoleForChainId(
      _chainId: BigNumberish,
      _role: BytesLike,
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasRoleForChainId(uint256,bytes32,address)"(
      _chainId: BigNumberish,
      _role: BytesLike,
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _initialOwner: string,
      _initialExecutionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,uint32)"(
      _initialOwner: string,
      _initialExecutionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    precommitSharedBridge(
      _chainAddress: string,
      _l2BlockNumber: BigNumberish,
      _l2Block: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "precommitSharedBridge(address,uint256,bytes)"(
      _chainAddress: string,
      _l2BlockNumber: BigNumberish,
      _l2Block: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    proveBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _proofData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "proveBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _proofData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    removeValidator(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeValidator(address,address)"(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    removeValidatorForChainId(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeValidatorForChainId(uint256,address)"(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    removeValidatorRoles(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeValidatorRoles(address,address,(bool,bool,bool,bool,bool))"(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    revertBatchesSharedBridge(
      _chainAddress: string,
      _newLastBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "revertBatchesSharedBridge(address,uint256)"(
      _chainAddress: string,
      _newLastBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setExecutionDelay(
      _executionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setExecutionDelay(uint32)"(
      _executionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    COMMITTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "COMMITTER_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    EXECUTOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "EXECUTOR_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    OPTIONAL_COMMITTER_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "OPTIONAL_COMMITTER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OPTIONAL_EXECUTOR_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "OPTIONAL_EXECUTOR_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OPTIONAL_PRECOMMITTER_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "OPTIONAL_PRECOMMITTER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OPTIONAL_PROVER_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "OPTIONAL_PROVER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OPTIONAL_REVERTER_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "OPTIONAL_REVERTER_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PRECOMMITTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PRECOMMITTER_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PROVER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PROVER_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REVERTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "REVERTER_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addValidator(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addValidator(address,address)"(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addValidatorForChainId(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addValidatorForChainId(uint256,address)"(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addValidatorRoles(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addValidatorRoles(address,address,(bool,bool,bool,bool,bool))"(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    commitBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "commitBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    executeBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _batchData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    executionDelay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "executionDelay()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCommittedBatchTimestamp(
      _chainAddress: string,
      _l2BatchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCommittedBatchTimestamp(address,uint256)"(
      _chainAddress: string,
      _l2BatchNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getName()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hasRoleForChainId(
      _chainId: BigNumberish,
      _role: BytesLike,
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasRoleForChainId(uint256,bytes32,address)"(
      _chainId: BigNumberish,
      _role: BytesLike,
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _initialOwner: string,
      _initialExecutionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,uint32)"(
      _initialOwner: string,
      _initialExecutionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    precommitSharedBridge(
      _chainAddress: string,
      _l2BlockNumber: BigNumberish,
      _l2Block: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "precommitSharedBridge(address,uint256,bytes)"(
      _chainAddress: string,
      _l2BlockNumber: BigNumberish,
      _l2Block: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    proveBatchesSharedBridge(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _proofData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "proveBatchesSharedBridge(address,uint256,uint256,bytes)"(
      _chainAddress: string,
      _processBatchFrom: BigNumberish,
      _processBatchTo: BigNumberish,
      _proofData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    removeValidator(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeValidator(address,address)"(
      _chainAddress: string,
      _validator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    removeValidatorForChainId(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeValidatorForChainId(uint256,address)"(
      _chainId: BigNumberish,
      _validator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    removeValidatorRoles(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeValidatorRoles(address,address,(bool,bool,bool,bool,bool))"(
      _chainAddress: string,
      _validator: string,
      params: {
        rotatePrecommitterRole: boolean;
        rotateCommitterRole: boolean;
        rotateReverterRole: boolean;
        rotateProverRole: boolean;
        rotateExecutorRole: boolean;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    revertBatchesSharedBridge(
      _chainAddress: string,
      _newLastBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revertBatchesSharedBridge(address,uint256)"(
      _chainAddress: string,
      _newLastBatch: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setExecutionDelay(
      _executionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setExecutionDelay(uint32)"(
      _executionDelay: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
