/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface L1GenesisUpgradeInterface extends ethers.utils.Interface {
  functions: {
    "genesisUpgrade(address,uint256,uint256,address,bytes,bytes[])": FunctionFragment;
    "upgrade(tuple)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "genesisUpgrade",
    values: [string, BigNumberish, BigNumberish, string, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "upgrade",
    values: [
      {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "genesisUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;

  events: {
    "DiamondCut(tuple[],address,bytes)": EventFragment;
    "GenesisUpgrade(address,tuple,uint256,bytes[])": EventFragment;
    "NewL2BootloaderBytecodeHash(bytes32,bytes32)": EventFragment;
    "NewL2DefaultAccountBytecodeHash(bytes32,bytes32)": EventFragment;
    "NewL2EvmEmulatorBytecodeHash(bytes32,bytes32)": EventFragment;
    "NewProtocolVersion(uint256,uint256)": EventFragment;
    "NewVerifier(address,address)": EventFragment;
    "NewVerifierParams(tuple,tuple)": EventFragment;
    "UpgradeComplete(uint256,bytes32,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DiamondCut"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GenesisUpgrade"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NewL2BootloaderBytecodeHash"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NewL2DefaultAccountBytecodeHash"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NewL2EvmEmulatorBytecodeHash"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewProtocolVersion"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewVerifier"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewVerifierParams"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpgradeComplete"): EventFragment;
}

export class L1GenesisUpgrade extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: L1GenesisUpgradeInterface;

  functions: {
    genesisUpgrade(
      _l1GenesisUpgrade: string,
      _chainId: BigNumberish,
      _protocolVersion: BigNumberish,
      _l1CtmDeployerAddress: string,
      _fixedForceDeploymentsData: BytesLike,
      _factoryDeps: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "genesisUpgrade(address,uint256,uint256,address,bytes,bytes[])"(
      _l1GenesisUpgrade: string,
      _chainId: BigNumberish,
      _protocolVersion: BigNumberish,
      _l1CtmDeployerAddress: string,
      _fixedForceDeploymentsData: BytesLike,
      _factoryDeps: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    upgrade(
      _proposedUpgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "upgrade(((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,uint256[],bytes,bytes),bytes32,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes,bytes,uint256,uint256))"(
      _proposedUpgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  genesisUpgrade(
    _l1GenesisUpgrade: string,
    _chainId: BigNumberish,
    _protocolVersion: BigNumberish,
    _l1CtmDeployerAddress: string,
    _fixedForceDeploymentsData: BytesLike,
    _factoryDeps: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "genesisUpgrade(address,uint256,uint256,address,bytes,bytes[])"(
    _l1GenesisUpgrade: string,
    _chainId: BigNumberish,
    _protocolVersion: BigNumberish,
    _l1CtmDeployerAddress: string,
    _fixedForceDeploymentsData: BytesLike,
    _factoryDeps: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  upgrade(
    _proposedUpgrade: {
      l2ProtocolUpgradeTx: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BigNumberish[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      };
      bootloaderHash: BytesLike;
      defaultAccountHash: BytesLike;
      evmEmulatorHash: BytesLike;
      verifier: string;
      verifierParams: {
        recursionNodeLevelVkHash: BytesLike;
        recursionLeafLevelVkHash: BytesLike;
        recursionCircuitsSetVksHash: BytesLike;
      };
      l1ContractsUpgradeCalldata: BytesLike;
      postUpgradeCalldata: BytesLike;
      upgradeTimestamp: BigNumberish;
      newProtocolVersion: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "upgrade(((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,uint256[],bytes,bytes),bytes32,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes,bytes,uint256,uint256))"(
    _proposedUpgrade: {
      l2ProtocolUpgradeTx: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BigNumberish[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      };
      bootloaderHash: BytesLike;
      defaultAccountHash: BytesLike;
      evmEmulatorHash: BytesLike;
      verifier: string;
      verifierParams: {
        recursionNodeLevelVkHash: BytesLike;
        recursionLeafLevelVkHash: BytesLike;
        recursionCircuitsSetVksHash: BytesLike;
      };
      l1ContractsUpgradeCalldata: BytesLike;
      postUpgradeCalldata: BytesLike;
      upgradeTimestamp: BigNumberish;
      newProtocolVersion: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    genesisUpgrade(
      _l1GenesisUpgrade: string,
      _chainId: BigNumberish,
      _protocolVersion: BigNumberish,
      _l1CtmDeployerAddress: string,
      _fixedForceDeploymentsData: BytesLike,
      _factoryDeps: BytesLike[],
      overrides?: CallOverrides
    ): Promise<string>;

    "genesisUpgrade(address,uint256,uint256,address,bytes,bytes[])"(
      _l1GenesisUpgrade: string,
      _chainId: BigNumberish,
      _protocolVersion: BigNumberish,
      _l1CtmDeployerAddress: string,
      _fixedForceDeploymentsData: BytesLike,
      _factoryDeps: BytesLike[],
      overrides?: CallOverrides
    ): Promise<string>;

    upgrade(
      _proposedUpgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    "upgrade(((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,uint256[],bytes,bytes),bytes32,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes,bytes,uint256,uint256))"(
      _proposedUpgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    DiamondCut(
      facetCuts: null,
      initAddress: null,
      initCalldata: null
    ): EventFilter;

    GenesisUpgrade(
      _zkChain: string | null,
      _l2Transaction: null,
      _protocolVersion: BigNumberish | null,
      _factoryDeps: null
    ): EventFilter;

    NewL2BootloaderBytecodeHash(
      previousBytecodeHash: BytesLike | null,
      newBytecodeHash: BytesLike | null
    ): EventFilter;

    NewL2DefaultAccountBytecodeHash(
      previousBytecodeHash: BytesLike | null,
      newBytecodeHash: BytesLike | null
    ): EventFilter;

    NewL2EvmEmulatorBytecodeHash(
      previousBytecodeHash: BytesLike | null,
      newBytecodeHash: BytesLike | null
    ): EventFilter;

    NewProtocolVersion(
      previousProtocolVersion: BigNumberish | null,
      newProtocolVersion: BigNumberish | null
    ): EventFilter;

    NewVerifier(
      oldVerifier: string | null,
      newVerifier: string | null
    ): EventFilter;

    NewVerifierParams(
      oldVerifierParams: null,
      newVerifierParams: null
    ): EventFilter;

    UpgradeComplete(
      newProtocolVersion: BigNumberish | null,
      l2UpgradeTxHash: BytesLike | null,
      upgrade: null
    ): EventFilter;
  };

  estimateGas: {
    genesisUpgrade(
      _l1GenesisUpgrade: string,
      _chainId: BigNumberish,
      _protocolVersion: BigNumberish,
      _l1CtmDeployerAddress: string,
      _fixedForceDeploymentsData: BytesLike,
      _factoryDeps: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "genesisUpgrade(address,uint256,uint256,address,bytes,bytes[])"(
      _l1GenesisUpgrade: string,
      _chainId: BigNumberish,
      _protocolVersion: BigNumberish,
      _l1CtmDeployerAddress: string,
      _fixedForceDeploymentsData: BytesLike,
      _factoryDeps: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    upgrade(
      _proposedUpgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "upgrade(((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,uint256[],bytes,bytes),bytes32,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes,bytes,uint256,uint256))"(
      _proposedUpgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    genesisUpgrade(
      _l1GenesisUpgrade: string,
      _chainId: BigNumberish,
      _protocolVersion: BigNumberish,
      _l1CtmDeployerAddress: string,
      _fixedForceDeploymentsData: BytesLike,
      _factoryDeps: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "genesisUpgrade(address,uint256,uint256,address,bytes,bytes[])"(
      _l1GenesisUpgrade: string,
      _chainId: BigNumberish,
      _protocolVersion: BigNumberish,
      _l1CtmDeployerAddress: string,
      _fixedForceDeploymentsData: BytesLike,
      _factoryDeps: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    upgrade(
      _proposedUpgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "upgrade(((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,uint256[],bytes,bytes),bytes32,bytes32,bytes32,address,(bytes32,bytes32,bytes32),bytes,bytes,uint256,uint256))"(
      _proposedUpgrade: {
        l2ProtocolUpgradeTx: {
          txType: BigNumberish;
          from: BigNumberish;
          to: BigNumberish;
          gasLimit: BigNumberish;
          gasPerPubdataByteLimit: BigNumberish;
          maxFeePerGas: BigNumberish;
          maxPriorityFeePerGas: BigNumberish;
          paymaster: BigNumberish;
          nonce: BigNumberish;
          value: BigNumberish;
          reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
          data: BytesLike;
          signature: BytesLike;
          factoryDeps: BigNumberish[];
          paymasterInput: BytesLike;
          reservedDynamic: BytesLike;
        };
        bootloaderHash: BytesLike;
        defaultAccountHash: BytesLike;
        evmEmulatorHash: BytesLike;
        verifier: string;
        verifierParams: {
          recursionNodeLevelVkHash: BytesLike;
          recursionLeafLevelVkHash: BytesLike;
          recursionCircuitsSetVksHash: BytesLike;
        };
        l1ContractsUpgradeCalldata: BytesLike;
        postUpgradeCalldata: BytesLike;
        upgradeTimestamp: BigNumberish;
        newProtocolVersion: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
