/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface L2SharedBridgeLegacyDevInterface extends ethers.utils.Interface {
  functions: {
    "deployBeaconProxy(bytes32)": FunctionFragment;
    "finalizeDeposit(address,address,address,uint256,bytes)": FunctionFragment;
    "initialize(address,bytes32,address)": FunctionFragment;
    "initializeDevBridge(address,address,bytes32,address)": FunctionFragment;
    "l1Bridge()": FunctionFragment;
    "l1SharedBridge()": FunctionFragment;
    "l1TokenAddress(address)": FunctionFragment;
    "l2TokenAddress(address)": FunctionFragment;
    "l2TokenBeacon()": FunctionFragment;
    "sendMessageToL1(bytes)": FunctionFragment;
    "withdraw(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deployBeaconProxy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDeposit",
    values: [string, string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeDevBridge",
    values: [string, string, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "l1Bridge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "l1SharedBridge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "l1TokenAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "l2TokenAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "l2TokenBeacon",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessageToL1",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployBeaconProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeDevBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "l1Bridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "l1SharedBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l1TokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2TokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2TokenBeacon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessageToL1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "FinalizeDeposit(address,address,address,uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FinalizeDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export class L2SharedBridgeLegacyDev extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: L2SharedBridgeLegacyDevInterface;

  functions: {
    deployBeaconProxy(
      salt: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deployBeaconProxy(bytes32)"(
      salt: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    finalizeDeposit(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "finalizeDeposit(address,address,address,uint256,bytes)"(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initialize(
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,bytes32,address)"(
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initializeDevBridge(
      _legacyBridge: string,
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initializeDevBridge(address,address,bytes32,address)"(
      _legacyBridge: string,
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    l1Bridge(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "l1Bridge()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    l1SharedBridge(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "l1SharedBridge()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    l1TokenAddress(
      l2TokenAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      l1TokenAddress: string;
      0: string;
    }>;

    "l1TokenAddress(address)"(
      l2TokenAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      l1TokenAddress: string;
      0: string;
    }>;

    l2TokenAddress(
      _l1Token: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "l2TokenAddress(address)"(
      _l1Token: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    l2TokenBeacon(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "l2TokenBeacon()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    sendMessageToL1(
      _message: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sendMessageToL1(bytes)"(
      _message: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdraw(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdraw(address,address,uint256)"(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  deployBeaconProxy(
    salt: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deployBeaconProxy(bytes32)"(
    salt: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  finalizeDeposit(
    _l1Sender: string,
    _l2Receiver: string,
    _l1Token: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "finalizeDeposit(address,address,address,uint256,bytes)"(
    _l1Sender: string,
    _l2Receiver: string,
    _l1Token: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initialize(
    _l1SharedBridge: string,
    _l2TokenProxyBytecodeHash: BytesLike,
    _aliasedOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,bytes32,address)"(
    _l1SharedBridge: string,
    _l2TokenProxyBytecodeHash: BytesLike,
    _aliasedOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initializeDevBridge(
    _legacyBridge: string,
    _l1SharedBridge: string,
    _l2TokenProxyBytecodeHash: BytesLike,
    _aliasedOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initializeDevBridge(address,address,bytes32,address)"(
    _legacyBridge: string,
    _l1SharedBridge: string,
    _l2TokenProxyBytecodeHash: BytesLike,
    _aliasedOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  l1Bridge(overrides?: CallOverrides): Promise<string>;

  "l1Bridge()"(overrides?: CallOverrides): Promise<string>;

  l1SharedBridge(overrides?: CallOverrides): Promise<string>;

  "l1SharedBridge()"(overrides?: CallOverrides): Promise<string>;

  l1TokenAddress(
    l2TokenAddress: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "l1TokenAddress(address)"(
    l2TokenAddress: string,
    overrides?: CallOverrides
  ): Promise<string>;

  l2TokenAddress(_l1Token: string, overrides?: CallOverrides): Promise<string>;

  "l2TokenAddress(address)"(
    _l1Token: string,
    overrides?: CallOverrides
  ): Promise<string>;

  l2TokenBeacon(overrides?: CallOverrides): Promise<string>;

  "l2TokenBeacon()"(overrides?: CallOverrides): Promise<string>;

  sendMessageToL1(
    _message: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sendMessageToL1(bytes)"(
    _message: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdraw(
    _l1Receiver: string,
    _l2Token: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdraw(address,address,uint256)"(
    _l1Receiver: string,
    _l2Token: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    deployBeaconProxy(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "deployBeaconProxy(bytes32)"(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    finalizeDeposit(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "finalizeDeposit(address,address,address,uint256,bytes)"(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,bytes32,address)"(
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initializeDevBridge(
      _legacyBridge: string,
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initializeDevBridge(address,address,bytes32,address)"(
      _legacyBridge: string,
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    l1Bridge(overrides?: CallOverrides): Promise<string>;

    "l1Bridge()"(overrides?: CallOverrides): Promise<string>;

    l1SharedBridge(overrides?: CallOverrides): Promise<string>;

    "l1SharedBridge()"(overrides?: CallOverrides): Promise<string>;

    l1TokenAddress(
      l2TokenAddress: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "l1TokenAddress(address)"(
      l2TokenAddress: string,
      overrides?: CallOverrides
    ): Promise<string>;

    l2TokenAddress(
      _l1Token: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "l2TokenAddress(address)"(
      _l1Token: string,
      overrides?: CallOverrides
    ): Promise<string>;

    l2TokenBeacon(overrides?: CallOverrides): Promise<string>;

    "l2TokenBeacon()"(overrides?: CallOverrides): Promise<string>;

    sendMessageToL1(
      _message: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "sendMessageToL1(bytes)"(
      _message: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    withdraw(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdraw(address,address,uint256)"(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    FinalizeDeposit(
      l1Sender: string | null,
      l2Receiver: string | null,
      l2Token: string | null,
      amount: null
    ): EventFilter;

    Initialized(version: null): EventFilter;
  };

  estimateGas: {
    deployBeaconProxy(
      salt: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deployBeaconProxy(bytes32)"(
      salt: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    finalizeDeposit(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "finalizeDeposit(address,address,address,uint256,bytes)"(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initialize(
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,bytes32,address)"(
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initializeDevBridge(
      _legacyBridge: string,
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initializeDevBridge(address,address,bytes32,address)"(
      _legacyBridge: string,
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    l1Bridge(overrides?: CallOverrides): Promise<BigNumber>;

    "l1Bridge()"(overrides?: CallOverrides): Promise<BigNumber>;

    l1SharedBridge(overrides?: CallOverrides): Promise<BigNumber>;

    "l1SharedBridge()"(overrides?: CallOverrides): Promise<BigNumber>;

    l1TokenAddress(
      l2TokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "l1TokenAddress(address)"(
      l2TokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2TokenAddress(
      _l1Token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "l2TokenAddress(address)"(
      _l1Token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2TokenBeacon(overrides?: CallOverrides): Promise<BigNumber>;

    "l2TokenBeacon()"(overrides?: CallOverrides): Promise<BigNumber>;

    sendMessageToL1(
      _message: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sendMessageToL1(bytes)"(
      _message: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdraw(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdraw(address,address,uint256)"(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployBeaconProxy(
      salt: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deployBeaconProxy(bytes32)"(
      salt: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    finalizeDeposit(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "finalizeDeposit(address,address,address,uint256,bytes)"(
      _l1Sender: string,
      _l2Receiver: string,
      _l1Token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,bytes32,address)"(
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initializeDevBridge(
      _legacyBridge: string,
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initializeDevBridge(address,address,bytes32,address)"(
      _legacyBridge: string,
      _l1SharedBridge: string,
      _l2TokenProxyBytecodeHash: BytesLike,
      _aliasedOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    l1Bridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "l1Bridge()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l1SharedBridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "l1SharedBridge()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l1TokenAddress(
      l2TokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "l1TokenAddress(address)"(
      l2TokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2TokenAddress(
      _l1Token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "l2TokenAddress(address)"(
      _l1Token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2TokenBeacon(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "l2TokenBeacon()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sendMessageToL1(
      _message: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sendMessageToL1(bytes)"(
      _message: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdraw(address,address,uint256)"(
      _l1Receiver: string,
      _l2Token: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
