/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MessageRootInterface extends ethers.utils.Interface {
  functions: {
    "BRIDGE_HUB()": FunctionFragment;
    "L1_CHAIN_ID()": FunctionFragment;
    "addChainBatchRoot(uint256,uint256,bytes32)": FunctionFragment;
    "addNewChain(uint256)": FunctionFragment;
    "chainCount()": FunctionFragment;
    "chainIndex(uint256)": FunctionFragment;
    "chainIndexToId(uint256)": FunctionFragment;
    "chainRegistered(uint256)": FunctionFragment;
    "getAggregatedRoot()": FunctionFragment;
    "getChainRoot(uint256)": FunctionFragment;
    "historicalRoot(uint256)": FunctionFragment;
    "initialize()": FunctionFragment;
    "sharedTree()": FunctionFragment;
    "updateFullTree()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BRIDGE_HUB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "L1_CHAIN_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addChainBatchRoot",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addNewChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "chainCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "chainIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "chainIndexToId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "chainRegistered",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAggregatedRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getChainRoot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "historicalRoot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sharedTree",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateFullTree",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "BRIDGE_HUB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "L1_CHAIN_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addChainBatchRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addNewChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chainCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chainIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainIndexToId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "chainRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAggregatedRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "historicalRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sharedTree", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateFullTree",
    data: BytesLike
  ): Result;

  events: {
    "AddedChain(uint256,uint256)": EventFragment;
    "AppendedChainBatchRoot(uint256,uint256,bytes32)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "NewChainRoot(uint256,bytes32,bytes32)": EventFragment;
    "NewInteropRoot(uint256,uint256,uint256,bytes32[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddedChain"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AppendedChainBatchRoot"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewChainRoot"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewInteropRoot"): EventFragment;
}

export class MessageRoot extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MessageRootInterface;

  functions: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    L1_CHAIN_ID(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "L1_CHAIN_ID()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    addChainBatchRoot(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _chainBatchRoot: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addChainBatchRoot(uint256,uint256,bytes32)"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _chainBatchRoot: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addNewChain(
      _chainId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addNewChain(uint256)"(
      _chainId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    chainCount(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "chainCount()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    chainIndex(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      chainIndex: BigNumber;
      0: BigNumber;
    }>;

    "chainIndex(uint256)"(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      chainIndex: BigNumber;
      0: BigNumber;
    }>;

    chainIndexToId(
      chainIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      chainId: BigNumber;
      0: BigNumber;
    }>;

    "chainIndexToId(uint256)"(
      chainIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      chainId: BigNumber;
      0: BigNumber;
    }>;

    chainRegistered(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "chainRegistered(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    getAggregatedRoot(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "getAggregatedRoot()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    getChainRoot(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getChainRoot(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    historicalRoot(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      globalMessageRoot: string;
      0: string;
    }>;

    "historicalRoot(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      globalMessageRoot: string;
      0: string;
    }>;

    initialize(overrides?: Overrides): Promise<ContractTransaction>;

    "initialize()"(overrides?: Overrides): Promise<ContractTransaction>;

    sharedTree(overrides?: CallOverrides): Promise<{
      _height: BigNumber;
      _leafNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "sharedTree()"(overrides?: CallOverrides): Promise<{
      _height: BigNumber;
      _leafNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    updateFullTree(overrides?: Overrides): Promise<ContractTransaction>;

    "updateFullTree()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

  "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

  L1_CHAIN_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "L1_CHAIN_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

  addChainBatchRoot(
    _chainId: BigNumberish,
    _batchNumber: BigNumberish,
    _chainBatchRoot: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addChainBatchRoot(uint256,uint256,bytes32)"(
    _chainId: BigNumberish,
    _batchNumber: BigNumberish,
    _chainBatchRoot: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addNewChain(
    _chainId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addNewChain(uint256)"(
    _chainId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  chainCount(overrides?: CallOverrides): Promise<BigNumber>;

  "chainCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  chainIndex(
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "chainIndex(uint256)"(
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  chainIndexToId(
    chainIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "chainIndexToId(uint256)"(
    chainIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  chainRegistered(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "chainRegistered(uint256)"(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getAggregatedRoot(overrides?: CallOverrides): Promise<string>;

  "getAggregatedRoot()"(overrides?: CallOverrides): Promise<string>;

  getChainRoot(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getChainRoot(uint256)"(
    _chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  historicalRoot(
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "historicalRoot(uint256)"(
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(overrides?: Overrides): Promise<ContractTransaction>;

  "initialize()"(overrides?: Overrides): Promise<ContractTransaction>;

  sharedTree(overrides?: CallOverrides): Promise<{
    _height: BigNumber;
    _leafNumber: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  "sharedTree()"(overrides?: CallOverrides): Promise<{
    _height: BigNumber;
    _leafNumber: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  updateFullTree(overrides?: Overrides): Promise<ContractTransaction>;

  "updateFullTree()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<string>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<string>;

    L1_CHAIN_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "L1_CHAIN_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    addChainBatchRoot(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _chainBatchRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "addChainBatchRoot(uint256,uint256,bytes32)"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _chainBatchRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    addNewChain(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "addNewChain(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    chainCount(overrides?: CallOverrides): Promise<BigNumber>;

    "chainCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    chainIndex(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "chainIndex(uint256)"(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chainIndexToId(
      chainIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "chainIndexToId(uint256)"(
      chainIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chainRegistered(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "chainRegistered(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getAggregatedRoot(overrides?: CallOverrides): Promise<string>;

    "getAggregatedRoot()"(overrides?: CallOverrides): Promise<string>;

    getChainRoot(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getChainRoot(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    historicalRoot(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "historicalRoot(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(overrides?: CallOverrides): Promise<void>;

    "initialize()"(overrides?: CallOverrides): Promise<void>;

    sharedTree(overrides?: CallOverrides): Promise<{
      _height: BigNumber;
      _leafNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "sharedTree()"(overrides?: CallOverrides): Promise<{
      _height: BigNumber;
      _leafNumber: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    updateFullTree(overrides?: CallOverrides): Promise<void>;

    "updateFullTree()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    AddedChain(
      chainId: BigNumberish | null,
      chainIndex: BigNumberish | null
    ): EventFilter;

    AppendedChainBatchRoot(
      chainId: BigNumberish | null,
      batchNumber: BigNumberish | null,
      chainBatchRoot: null
    ): EventFilter;

    Initialized(version: null): EventFilter;

    NewChainRoot(
      chainId: BigNumberish | null,
      chainRoot: null,
      chainIdLeafHash: null
    ): EventFilter;

    NewInteropRoot(
      chainId: BigNumberish | null,
      blockNumber: BigNumberish | null,
      logId: BigNumberish | null,
      sides: null
    ): EventFilter;
  };

  estimateGas: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<BigNumber>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<BigNumber>;

    L1_CHAIN_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "L1_CHAIN_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    addChainBatchRoot(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _chainBatchRoot: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addChainBatchRoot(uint256,uint256,bytes32)"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _chainBatchRoot: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addNewChain(
      _chainId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addNewChain(uint256)"(
      _chainId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    chainCount(overrides?: CallOverrides): Promise<BigNumber>;

    "chainCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    chainIndex(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "chainIndex(uint256)"(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chainIndexToId(
      chainIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "chainIndexToId(uint256)"(
      chainIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chainRegistered(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "chainRegistered(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAggregatedRoot(overrides?: CallOverrides): Promise<BigNumber>;

    "getAggregatedRoot()"(overrides?: CallOverrides): Promise<BigNumber>;

    getChainRoot(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getChainRoot(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    historicalRoot(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "historicalRoot(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(overrides?: Overrides): Promise<BigNumber>;

    "initialize()"(overrides?: Overrides): Promise<BigNumber>;

    sharedTree(overrides?: CallOverrides): Promise<BigNumber>;

    "sharedTree()"(overrides?: CallOverrides): Promise<BigNumber>;

    updateFullTree(overrides?: Overrides): Promise<BigNumber>;

    "updateFullTree()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BRIDGE_HUB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "BRIDGE_HUB()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    L1_CHAIN_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "L1_CHAIN_ID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addChainBatchRoot(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _chainBatchRoot: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addChainBatchRoot(uint256,uint256,bytes32)"(
      _chainId: BigNumberish,
      _batchNumber: BigNumberish,
      _chainBatchRoot: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addNewChain(
      _chainId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addNewChain(uint256)"(
      _chainId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    chainCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "chainCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    chainIndex(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "chainIndex(uint256)"(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    chainIndexToId(
      chainIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "chainIndexToId(uint256)"(
      chainIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    chainRegistered(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "chainRegistered(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAggregatedRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getAggregatedRoot()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChainRoot(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getChainRoot(uint256)"(
      _chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    historicalRoot(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "historicalRoot(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(overrides?: Overrides): Promise<PopulatedTransaction>;

    "initialize()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    sharedTree(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "sharedTree()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateFullTree(overrides?: Overrides): Promise<PopulatedTransaction>;

    "updateFullTree()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
