/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ReenterL1ERC20BridgeInterface extends ethers.utils.Interface {
  functions: {
    "setBridge(address)": FunctionFragment;
    "setFunctionToCall(uint8)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "setBridge", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setFunctionToCall",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "setBridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFunctionToCall",
    data: BytesLike
  ): Result;

  events: {};
}

export class ReenterL1ERC20Bridge extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ReenterL1ERC20BridgeInterface;

  functions: {
    setBridge(
      _l1Erc20Bridge: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setBridge(address)"(
      _l1Erc20Bridge: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setFunctionToCall(
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setFunctionToCall(uint8)"(
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  setBridge(
    _l1Erc20Bridge: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setBridge(address)"(
    _l1Erc20Bridge: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setFunctionToCall(
    _functionToCall: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setFunctionToCall(uint8)"(
    _functionToCall: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    setBridge(_l1Erc20Bridge: string, overrides?: CallOverrides): Promise<void>;

    "setBridge(address)"(
      _l1Erc20Bridge: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFunctionToCall(
      _functionToCall: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setFunctionToCall(uint8)"(
      _functionToCall: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    setBridge(
      _l1Erc20Bridge: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setBridge(address)"(
      _l1Erc20Bridge: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setFunctionToCall(
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setFunctionToCall(uint8)"(
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setBridge(
      _l1Erc20Bridge: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setBridge(address)"(
      _l1Erc20Bridge: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setFunctionToCall(
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setFunctionToCall(uint8)"(
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
