/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { RevertReceiveAccount } from "./RevertReceiveAccount";

export class RevertReceiveAccountFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<RevertReceiveAccount> {
    return super.deploy(overrides || {}) as Promise<RevertReceiveAccount>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): RevertReceiveAccount {
    return super.attach(address) as RevertReceiveAccount;
  }
  connect(signer: Signer): RevertReceiveAccountFactory {
    return super.connect(signer) as RevertReceiveAccountFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RevertReceiveAccount {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as RevertReceiveAccount;
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "revertReceive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "newValue",
        type: "bool",
      },
    ],
    name: "setRevertReceive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x0000008003000039000000400030043f0000000100200190000000180000c13d00000060021002700000001202200197000000040020008c000000230000413d000000000301043b000000e003300270000000160030009c0000002a0000613d000000170030009c0000003c0000c13d0000000001000416000000000001004b0000003c0000c13d000000000100041a000000ff001001900000000001000039000000010100c039000000800010043f0000001801000041000000450001042e0000000001000416000000000001004b0000003c0000c13d000000000200041a0000001901200197000000000010041b0000002001000039000001000010044300000120000004430000001301000041000000450001042e000000000002004b0000003c0000c13d000000000100041a000000ff001001900000003e0000c13d0000000001000019000000450001042e000000240020008c0000003c0000413d0000000002000416000000000002004b0000003c0000c13d0000000401100370000000000101043b000000000001004b0000000002000039000000010200c039000000000021004b0000003c0000c13d000000000300041a0000001902300197000000000112019f000000000010041b0000000001000019000000450001042e000000000100001900000046000104300000001401000041000000000010043f0000000101000039000000040010043f000000150100004100000046000104300000004400000432000000450001042e0000004600010430000000000000000000000000000000000000000000000000000000000000000000000000ffffffff00000002000000000000000000000000000000400000010000000000000000004e487b7100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002400000000000000000000000000000000000000000000000000000000000000000000000000000000607e2cb200000000000000000000000000000000000000000000000000000000aa4593dc0000000000000000000000000000000000000020000000800000000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00d0293e58314232e51acf59343ac720999166a38a9f32ea8f7bc29fef90831a30";
