/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface UpgradeStageValidatorInterface extends ethers.utils.Interface {
  functions: {
    "BRIDGEHUB()": FunctionFragment;
    "CHAIN_TYPE_MANAGER()": FunctionFragment;
    "NEW_PROTOCOL_VERSION()": FunctionFragment;
    "checkMigrationsPaused()": FunctionFragment;
    "checkMigrationsUnpaused()": FunctionFragment;
    "checkProtocolUpgradePresence()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "BRIDGEHUB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CHAIN_TYPE_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NEW_PROTOCOL_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkMigrationsPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkMigrationsUnpaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkProtocolUpgradePresence",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "BRIDGEHUB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CHAIN_TYPE_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NEW_PROTOCOL_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkMigrationsPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkMigrationsUnpaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkProtocolUpgradePresence",
    data: BytesLike
  ): Result;

  events: {};
}

export class UpgradeStageValidator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: UpgradeStageValidatorInterface;

  functions: {
    BRIDGEHUB(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "BRIDGEHUB()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    CHAIN_TYPE_MANAGER(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "CHAIN_TYPE_MANAGER()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    NEW_PROTOCOL_VERSION(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "NEW_PROTOCOL_VERSION()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    checkMigrationsPaused(overrides?: Overrides): Promise<ContractTransaction>;

    "checkMigrationsPaused()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    checkMigrationsUnpaused(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkMigrationsUnpaused()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    checkProtocolUpgradePresence(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkProtocolUpgradePresence()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  BRIDGEHUB(overrides?: CallOverrides): Promise<string>;

  "BRIDGEHUB()"(overrides?: CallOverrides): Promise<string>;

  CHAIN_TYPE_MANAGER(overrides?: CallOverrides): Promise<string>;

  "CHAIN_TYPE_MANAGER()"(overrides?: CallOverrides): Promise<string>;

  NEW_PROTOCOL_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

  "NEW_PROTOCOL_VERSION()"(overrides?: CallOverrides): Promise<BigNumber>;

  checkMigrationsPaused(overrides?: Overrides): Promise<ContractTransaction>;

  "checkMigrationsPaused()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  checkMigrationsUnpaused(overrides?: Overrides): Promise<ContractTransaction>;

  "checkMigrationsUnpaused()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  checkProtocolUpgradePresence(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "checkProtocolUpgradePresence()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    BRIDGEHUB(overrides?: CallOverrides): Promise<string>;

    "BRIDGEHUB()"(overrides?: CallOverrides): Promise<string>;

    CHAIN_TYPE_MANAGER(overrides?: CallOverrides): Promise<string>;

    "CHAIN_TYPE_MANAGER()"(overrides?: CallOverrides): Promise<string>;

    NEW_PROTOCOL_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    "NEW_PROTOCOL_VERSION()"(overrides?: CallOverrides): Promise<BigNumber>;

    checkMigrationsPaused(overrides?: CallOverrides): Promise<void>;

    "checkMigrationsPaused()"(overrides?: CallOverrides): Promise<void>;

    checkMigrationsUnpaused(overrides?: CallOverrides): Promise<void>;

    "checkMigrationsUnpaused()"(overrides?: CallOverrides): Promise<void>;

    checkProtocolUpgradePresence(overrides?: CallOverrides): Promise<void>;

    "checkProtocolUpgradePresence()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    BRIDGEHUB(overrides?: CallOverrides): Promise<BigNumber>;

    "BRIDGEHUB()"(overrides?: CallOverrides): Promise<BigNumber>;

    CHAIN_TYPE_MANAGER(overrides?: CallOverrides): Promise<BigNumber>;

    "CHAIN_TYPE_MANAGER()"(overrides?: CallOverrides): Promise<BigNumber>;

    NEW_PROTOCOL_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    "NEW_PROTOCOL_VERSION()"(overrides?: CallOverrides): Promise<BigNumber>;

    checkMigrationsPaused(overrides?: Overrides): Promise<BigNumber>;

    "checkMigrationsPaused()"(overrides?: Overrides): Promise<BigNumber>;

    checkMigrationsUnpaused(overrides?: Overrides): Promise<BigNumber>;

    "checkMigrationsUnpaused()"(overrides?: Overrides): Promise<BigNumber>;

    checkProtocolUpgradePresence(overrides?: Overrides): Promise<BigNumber>;

    "checkProtocolUpgradePresence()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BRIDGEHUB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "BRIDGEHUB()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CHAIN_TYPE_MANAGER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "CHAIN_TYPE_MANAGER()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    NEW_PROTOCOL_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "NEW_PROTOCOL_VERSION()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkMigrationsPaused(overrides?: Overrides): Promise<PopulatedTransaction>;

    "checkMigrationsPaused()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    checkMigrationsUnpaused(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkMigrationsUnpaused()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    checkProtocolUpgradePresence(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkProtocolUpgradePresence()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
